
const ACTION_TYPE = {
	SIGN_UP: 'SIGN_UP',
	LOG_OUT: 'LOG_OUT',
	ADD_NEW_RIDE: 'ADD_NEW_RIDE',
	VIEW_ALL_RIDES: 'VIEW_ALL_RIDES',
	RIDE_ERRORS: 'RIDE_ERRORS',
	DELETE_RIDE: 'DELETE_RIDE',
	VIEW_ALL_REQUESTS: 'VIEW_ALL_REQUESTS'
};

export default ACTION_TYPE;
